# Generated by Django 4.2.2 on 2023-06-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_manager', '0002_manager_company_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='email',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='email',
        ),
    ]
