# Generated by Django 4.2.2 on 2023-06-27 06:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_manager', '0005_hpc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hpc',
            new_name='headplacementcoordinator',
        ),
    ]
